package sn.sonatel.dsi.ins.ftsirc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetriqueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetriqueAllPropertiesEquals(Metrique expected, Metrique actual) {
        assertMetriqueAutoGeneratedPropertiesEquals(expected, actual);
        assertMetriqueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetriqueAllUpdatablePropertiesEquals(Metrique expected, Metrique actual) {
        assertMetriqueUpdatableFieldsEquals(expected, actual);
        assertMetriqueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetriqueAutoGeneratedPropertiesEquals(Metrique expected, Metrique actual) {
        assertThat(expected)
            .as("Verify Metrique auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetriqueUpdatableFieldsEquals(Metrique expected, Metrique actual) {
        assertThat(expected)
            .as("Verify Metrique relevant properties")
            .satisfies(e -> assertThat(e.getOltPower()).as("check oltPower").isEqualTo(actual.getOltPower()))
            .satisfies(e -> assertThat(e.getOntPower()).as("check ontPower").isEqualTo(actual.getOntPower()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetriqueUpdatableRelationshipsEquals(Metrique expected, Metrique actual) {
        assertThat(expected)
            .as("Verify Metrique relationships")
            .satisfies(e -> assertThat(e.getOnt()).as("check ont").isEqualTo(actual.getOnt()));
    }
}
