package sn.sonatel.dsi.ins.ftsirc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeDiagnosticAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDiagnosticAllPropertiesEquals(TypeDiagnostic expected, TypeDiagnostic actual) {
        assertTypeDiagnosticAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeDiagnosticAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDiagnosticAllUpdatablePropertiesEquals(TypeDiagnostic expected, TypeDiagnostic actual) {
        assertTypeDiagnosticUpdatableFieldsEquals(expected, actual);
        assertTypeDiagnosticUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDiagnosticAutoGeneratedPropertiesEquals(TypeDiagnostic expected, TypeDiagnostic actual) {
        assertThat(expected)
            .as("Verify TypeDiagnostic auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDiagnosticUpdatableFieldsEquals(TypeDiagnostic expected, TypeDiagnostic actual) {
        assertThat(expected)
            .as("Verify TypeDiagnostic relevant properties")
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDiagnosticUpdatableRelationshipsEquals(TypeDiagnostic expected, TypeDiagnostic actual) {}
}
